#!/usr/bin/env bash
# =============================================================================
# generate_jvm_args.sh — Writes user_jvm_args.txt with correct memory flags
# Called during install or on first boot to configure JVM heap based on the
# RAM allocated to this server in Pterodactyl.
#
# Pterodactyl exposes container RAM as SERVER_MEMORY (in MB).
# We use 85% of that for -Xmx and 25% for -Xms, leaving headroom for the OS,
# off-heap memory, and Forge's own native allocations.
#
# USAGE:
#   bash generate_jvm_args.sh
# =============================================================================

set -euo pipefail

OUTPUT="${SERVER_DIR:-/home/container}/user_jvm_args.txt"

log() { echo "[jvm_args] $*"; }

# --- Detect available RAM ---
# SERVER_MEMORY is set by Pterodactyl in MB (e.g. 10240 for 10GB)
# Fall back to 8192MB (8GB) if not set
RAW_MB="${SERVER_MEMORY:-8192}"

# Strip any non-numeric characters just in case
RAW_MB="${RAW_MB//[^0-9]/}"

if [[ -z "$RAW_MB" || "$RAW_MB" -lt 1024 ]]; then
  log "WARN: SERVER_MEMORY is unset or too low ($RAW_MB MB), defaulting to 8192 MB"
  RAW_MB=8192
fi

# Calculate Xmx as 85% of total, Xms as 25%
XMX_MB=$(( RAW_MB * 85 / 100 ))
XMS_MB=$(( RAW_MB * 25 / 100 ))

# Convert to GB if clean, otherwise keep as MB
if (( XMX_MB % 1024 == 0 )); then
  XMX="${XMX_MB}M"
  XMX_DISPLAY="$(( XMX_MB / 1024 ))G"
else
  XMX="${XMX_MB}M"
  XMX_DISPLAY="${XMX_MB}M"
fi

if (( XMS_MB % 1024 == 0 )); then
  XMS="${XMS_MB}M"
  XMS_DISPLAY="$(( XMS_MB / 1024 ))G"
else
  XMS="${XMS_MB}M"
  XMS_DISPLAY="${XMS_MB}M"
fi

log "SERVER_MEMORY=${RAW_MB}MB → Xmx=${XMX_DISPLAY}, Xms=${XMS_DISPLAY}"

# --- Write the file ---
cat > "$OUTPUT" << EOF
# Auto-generated by generate_jvm_args.sh
# SERVER_MEMORY=${RAW_MB}MB → Xmx=${XMX_DISPLAY}, Xms=${XMS_DISPLAY}
# To regenerate: bash generate_jvm_args.sh
-Xmx${XMX}
-Xms${XMS}
-XX:+UseG1GC
-XX:+ParallelRefProcEnabled
-XX:MaxGCPauseMillis=200
-XX:+UnlockExperimentalVMOptions
-XX:+DisableExplicitGC
-XX:G1NewSizePercent=30
-XX:G1MaxNewSizePercent=40
-XX:G1HeapRegionSize=8M
-XX:G1ReservePercent=20
-XX:G1HeapWastePercent=5
-XX:G1MixedGCCountTarget=4
-XX:InitiatingHeapOccupancyPercent=15
-XX:G1MixedGCLiveThresholdPercent=90
-XX:G1RSetUpdatingPauseTimePercent=5
-XX:SurvivorRatio=32
EOF

log "Written to $OUTPUT"
